sub-color='#fceed6' #subtitle color in rgb
sub-shadow-color='#000000' #shadow color
sub-font='LigaConsolas Nerd Font' #set sub-font
sub-bold=no
sub-blur=20
sub-font-size=35
sub-pos=88 #subtitle position x percent above the bottom of the screen
